apiVersion: v1
kind: ConfigMap
metadata:
  name: openproject-mcp-env
data:
  ENVIRONMENT: "prod"
  LOG_LEVEL: "INFO"
  OPENPROJECT_BASE_URL: "https://openproject.t3ja.com"
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "AWS_MSK_IAM"
