apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openproject-mcp-prod
namePrefix: prod-

labels:
  - includeSelectors: false
    pairs:
      environment: prod

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: openproject-mcp
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: openproject-mcp-env

images:
  - name: gsst3ja/openproject-mcp
    newTag: prod
