apiVersion: v1
kind: ConfigMap
metadata:
  name: openproject-mcp-env
  labels:
    app.kubernetes.io/name: openproject-mcp
data:
  MCP_TRANSPORT: "http+sse"
  LOG_LEVEL: "INFO"
  OPENPROJECT_BASE_URL: "https://openproject.t3ja.com"
  KAFKA_BOOTSTRAP: ""
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"
  ENVIRONMENT: "base"
